// Generated by GuardChain
export interface Transaction {
  id?: string;
  transactionId: string;
  amount: number;
  currency: string;
  fromAccount: string;
  toAccount: string;
  description?: string | null;
  timestamp: Date;
  status: string;
  riskScore: number;
  isBlacklisted: boolean;
  isFlagged: boolean;
  metadata?: string | null;
  createdAt: Date;
  updatedAt: Date;
}

export interface TransactionInput {
  transactionId: string;
  amount: number;
  currency: string;
  fromAccount: string;
  toAccount: string;
  description?: string;
  ipAddress?: string;
  userAgent?: string;
  location?: string;
  deviceId?: string;
  metadata?: any;
}

export interface Alert {
  id: string;
  title: string;
  description: string;
  severity: "LOW" | "MEDIUM" | "HIGH" | "CRITICAL";
  status: "PENDING" | "INVESTIGATING" | "RESOLVED" | "FALSE_POSITIVE";
  riskScore: number;
  category: string;
  metadata?: string;
  createdAt: Date;
  updatedAt: Date;
  transactionId?: string;
  assignedToId?: string;
}

export interface Investigation {
  id: string;
  title: string;
  description: string;
  status: "OPEN" | "IN_PROGRESS" | "CLOSED" | "ESCALATED";
  priority: "LOW" | "MEDIUM" | "HIGH" | "CRITICAL";
  createdAt: Date;
  updatedAt: Date;
  assignedToId?: string;
  alertId?: string;
  transactionIds: string[];
}
