import { NextApiRequest, NextApiResponse } from "next";

export default function handler(req: NextApiRequest, res: NextApiResponse) {
  // Dummy data for initial alerts
  res.status(200).json([
    {
      id: "1",
      alertId: "ALERT-001",
      transactionId: "TX-001",
      accountId: "****1234",
      alertType: "AMOUNT_ANOMALY",
      severity: "HIGH",
      status: "OPEN",
      riskScore: 85,
      riskFactors: [],
      description: "Transaksi melebihi batas normal 5x lipat",
      assignedTo: null,
      detectedAt: new Date().toISOString(),
      resolvedAt: null,
      evidence: [],
      modelVersion: "v1.0",
      confidence: 0.98,
      tags: [],
      notes: [],
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: "2",
      alertId: "ALERT-002",
      transactionId: "TX-002",
      accountId: "****5678",
      alertType: "PATTERN_MATCH",
      severity: "CRITICAL",
      status: "UNDER_REVIEW",
      riskScore: 92,
      riskFactors: [],
      description: "Pola transfer mencurigakan terdeteksi",
      assignedTo: null,
      detectedAt: new Date().toISOString(),
      resolvedAt: null,
      evidence: [],
      modelVersion: "v1.0",
      confidence: 0.99,
      tags: [],
      notes: [],
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: "3",
      alertId: "ALERT-003",
      transactionId: "TX-003",
      accountId: "****9012",
      alertType: "VELOCITY_CHECK",
      severity: "MEDIUM",
      status: "RESOLVED",
      riskScore: 70,
      riskFactors: [],
      description: "Frekuensi transaksi tinggi dalam waktu singkat",
      assignedTo: null,
      detectedAt: new Date().toISOString(),
      resolvedAt: new Date().toISOString(),
      evidence: [],
      modelVersion: "v1.0",
      confidence: 0.95,
      tags: [],
      notes: [],
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: "4",
      alertId: "ALERT-004",
      transactionId: "TX-004",
      accountId: "****3456",
      alertType: "NETWORK_RISK",
      severity: "HIGH",
      status: "ESCALATED",
      riskScore: 88,
      riskFactors: [],
      description: "Koneksi dengan akun berisiko tinggi",
      assignedTo: null,
      detectedAt: new Date().toISOString(),
      resolvedAt: null,
      evidence: [],
      modelVersion: "v1.0",
      confidence: 0.97,
      tags: [],
      notes: [],
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
  ]);
}
